Abomination:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Asksvin:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Asksvin_hatchling:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Aspect_Bonemass:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Aspect_Eikthyr:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Aspect_Elder:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Aspect_Fader:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Aspect_Moder:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Aspect_SeekerQueen:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Aspect_TentaRoot:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Aspect_Yagluth:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Barka:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Bat:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Bat_Swamp:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Bjorn:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Bjorn_sleeping:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Bjorn_spiritcaller:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Blob:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BlobAspect:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BlobElite:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BlobFrost:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BlobLava:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BlobMork:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BlobMorkMini:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BlobTar:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Boar:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Boar_piggy:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Boar_spiritcaller:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BogWitchKvastur:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Bonemass:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BonemawSerpent:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Charred_Archer:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Charred_Archer_Fader:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Charred_Mage:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Charred_Melee:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Charred_Melee_Dyrnwyn:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Charred_Melee_Fader:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Charred_Twitcher:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Charred_Twitcher_Summoned:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Chicken:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Deathsquito:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Deer:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Deer_White:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Dragon:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Draugr:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Draugr_Elite:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Draugr_Elite_sleeping:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Draugr_Ranged:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Draugr_Ranged_sleeping:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Draugr_sleeping:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Dverger:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
DvergerAshlands:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
DvergerDeepNorth:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
DvergerMage:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
DvergerMageFire:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
DvergerMageIce:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
DvergerMageSupport:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
DvergerTest:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Eikthyr:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Elaking:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
ElakingLantern:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
ElakingMole:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Fader:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
FallenValkyrie:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
FallenWarrior:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Fenring:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Fenring_Cultist:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Fenring_Cultist_Hildir:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Fenring_Cultist_Hildir_nochest:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
FrostWisp:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
FrozenKing:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
FrozenKing_p2:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
FrozenKing_p3:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Frysling:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
gd_king:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Ghost:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Ghost_old:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Ghost_sleeping:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Ghost_Void:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Gjall:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Goblin:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Goblin_Gem:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GoblinArcher:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GoblinBrute:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GoblinBrute_Hildir:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GoblinBruteBros:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GoblinBruteBros_nochest:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GoblinDeepNorth:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GoblinKing:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GoblinShaman:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GoblinShaman_Hildir:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GoblinShaman_Hildir_nochest:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Greydwarf:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Greydwarf_Elite:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Greydwarf_Frozen:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Greydwarf_Shaman:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Greydwarf_Shaman_Frozen:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Greyling:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Hare:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Hatchling:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Hen:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Hive:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
JotunWarrior:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
JotunWarriorDualWield:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
JotunWitch:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Leech:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Leech_cave:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Lox:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Lox_Calf:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Mistile:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Moose:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Moose_calf:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Moose_spiritcaller:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Morgen:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Morgen_NonSleeping:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Neck:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
piece_TrainingDummy:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Seal:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Seal_Pup:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Seeker:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
SeekerBrood:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
SeekerBrute:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
SeekerQueen:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Serpent:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
ShadowPerson:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton_aspect:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton_DeepNorth:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton_Friendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton_Hildir:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton_Hildir_nochest:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton_Meadows:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton_Meadows_noarcher:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton_Mountains:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton_Mountains_noarcher:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton_NoArcher:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton_Poison:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton_Swamps:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Skeleton_Swamps_noarcher:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
staff_greenroots_tentaroot:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
StoneGolem:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Surtling:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Tendril:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Tendril_back:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
TentaRoot:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
TentaRoot_wild:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
TheHive:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Tick:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
TrainingDummy:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Troll:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Troll_sleeping:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Troll_Summoned:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
TrollFrost:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Ulv:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Unbjorn:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Volture:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Wolf:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Wolf_cub:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Wolf_spiritcaller:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Wraith:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Writhan:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_FierySlime_Friendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_IcycleSlime_Friendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_LightningSlime_Friendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_ToxicSlime_Friendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
rae_Offspring_Normal:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
rae_OdinHorse:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BossAsmodeus_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Fox_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
FoxCub_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Razorback_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
RazorbackPiggy_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BossSvalt_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BurningHunger_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GDAncientShaman_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GDAncientShaman_rootspawn_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
RottingElk_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Crawler_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BossVrykolathas_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
DamnedOne_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
HelWraith_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
ObsidianGolem_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GrizzlyBear_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GrizzlyBearCub_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Prowler_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
ProwlerCub_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Shark_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
SummonedSurtling_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
SummonedGolem_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Sheep_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Lamb_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GreydwarfMage_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
SkeletonMage_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
FenringMage_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
GoblinMage_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
Staff_root_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
CorruptedDvergerMage_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
SummonedSeeker_TW:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_NeckFriendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_CultistFriendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_ArmoredSkellies:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_AsksvinFriendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_CharredRangeFriendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_CharredMeleeFriendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_HatchlingFriendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_SeekerBruteFriendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_ValkyrieFriendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_BjornFriendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
BMP_VileFriendly:
  Spring: true
  Summer: true
  Fall: true
  Winter: true
